@startuml uml

class "Rectangulo" as rectangulo{
    -double ancho = 1.0
    -double alto = 1.0

    +double getAncho()
    +void setAncho(ancho)
    +double getAlto()
    +void setAlto(alto)

    ~toString()

    +double calcArea(ancho, alto)
    +double calcPerim(ancho, alto)
}

@enduml